# ============================================================
#                       ECRATES
# ============================================================

language: en

create-distance: 6

timer:
  enabled: true

  # Used if a crate does not have its own seconds value.
  default-seconds: 3600

gui:
  crate-title: "&8&l%crate% Crate"
  editor-title: "&8&lEdit Rewards: %crate%"
  confirm-title: "&8&lConfirm Reward"

effects:
  enabled: true

crates:

  common:
    display-name: "&aCommon"
    seconds: 3600

  rare:
    display-name: "&bRare"
    seconds: 7200

  epic:
    display-name: "&dEpic"
    seconds: 10800
