name: ECrates
version: 1.0.0
main: com.elyther.ecrates.ECrates
api-version: '1.21'

author: Elyther
description: Virtual selectable crates with timers, GUI and effects.

softdepend:
  - PlaceholderAPI

commands:
  crate:
    description: ECrates main command
    usage: /crate
    aliases:
      - crates

permissions:
  ecrates.admin:
    description: Allows administration of ECrates
    default: op
